### ISSUE TITLE
TestHTTPUnavailable fails 

### ISSUE THREAD

**Issue by phumpal** [chromium/hstspreload#115] opened 2020-06-05 07:26 UTC
TestHTTPUnavailable fails as the cert for https://oskuro.net/ has expired

https://www.sslshopper.com/ssl-checker.html#hostname=oskuro.net

**Comment by phumpal** [comment] 2020-06-05 07:40
I believe this is @jmallach. Gentle ping ^^

**Comment by nharper** [comment] 2020-06-05 18:36
Some tests depend on the behavior of external domains and need to be rewritten to be hermetic.

Duplicate of #112

**Closed by nharper** 2020-06-05 18:36 UTC

**Comment by phumpal** [comment] 2020-06-05 22:58
Awesome thanks @jmallach
