### ISSUE TITLE
TestHTTPUnavailable fails

### ISSUE THREAD

**Issue by rwky** [chromium/hstspreload#114] opened 2019-12-13 17:20 UTC
The test is failing because it expects oskuro.net to not be available over plain http but it currently is.

https://github.com/chromium/hstspreload/blob/master/redirects_test.go#L129-L161

**Comment by nharper** [comment] 2020-06-05 18:36
Some tests depend on the behavior of external domains and need to be rewritten to be hermetic.

Duplicate of #112

**Closed by nharper** 2020-06-05 18:36 UTC
